name: Release pull requests
on:
  push:
    tags:
      - prerelease/*

jobs:
  prerelease:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout all
        with:
          fetch-depth: 0
