name: Upgrade Sandwich
on:
  workflow_dispatch:
    inputs:
      sandwich_version:
        description: 'Sandwich version'
        required: true
        default: '0.0.0'

jobs:
  upgrade:
    name: Upgrade Sandwich version
    needs: [ release_pull_requests ]
    runs-on: ubuntu-latest
    env:
      sandwich_version: ${{ github.event.inputs.sandwich_version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: release/7.3.2

      - name: Bump Sandwich version
        run: |
          fastlane upgrade_sandwich version:$sandwich_version

      - name: Commit changes
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git commit -am "Sandwich version upgraded to $sandwich_version"
          git push